# Generated by Django 3.1.5 on 2021-03-12 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='category_details',
            fields=[
                ('category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('category_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SellerTable',
            fields=[
                ('Seller_ID', models.AutoField(primary_key=True, serialize=False)),
                ('sellername', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=10)),
                ('date_of_birth', models.DateTimeField()),
                ('adress', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=20)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('price', models.IntegerField()),
                ('Seller_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshoppieapp.sellertable')),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshoppieapp.category_details')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
                ('Order_date', models.DateTimeField()),
                ('Expected_Delivery', models.DateTimeField()),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshoppieapp.producttable')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshoppieapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshoppieapp.producttable')),
            ],
        ),
    ]
