# Generated by Django 3.1.5 on 2021-04-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshoppieapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshoppieapp.user'),
        ),
        migrations.AddField(
            model_name='producttable',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
