# Generated by Django 3.1.5 on 2021-04-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshoppieapp', '0002_auto_20210405_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
