# Generated by Django 3.1.5 on 2021-04-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshoppieapp', '0003_auto_20210405_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='TotalPrice',
        ),
        migrations.AlterField(
            model_name='sellertable',
            name='sellername',
            field=models.CharField(db_column='sname', max_length=20),
        ),
        migrations.AlterModelTable(
            name='sellertable',
            table='tb_seler',
        ),
    ]
